"""add champ photo on utilisateur

Revision ID: 00c45fdd16f7
Revises: f16a6e8bb590
Create Date: 2025-09-10 10:10:28.362218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00c45fdd16f7'
down_revision = 'f16a6e8bb590'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contenu', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('contenu_id_prompt_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('contenu_id_template_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('contenu_id_model_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('contenu_id_utilisateur_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'prompt', ['id_prompt'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'model_ia', ['id_model'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'utilisateurs', ['id_utilisateur'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'templates', ['id_template'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('utilisateurs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(length=255), nullable=True))
        batch_op.alter_column('prenom',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('mot_de_passe',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateurs', schema=None) as batch_op:
        batch_op.alter_column('mot_de_passe',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('prenom',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('photo')

    with op.batch_alter_table('contenu', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('contenu_id_utilisateur_fkey'), 'utilisateurs', ['id_utilisateur'], ['id'])
        batch_op.create_foreign_key(batch_op.f('contenu_id_model_fkey'), 'model_ia', ['id_model'], ['id'])
        batch_op.create_foreign_key(batch_op.f('contenu_id_template_fkey'), 'templates', ['id_template'], ['id'])
        batch_op.create_foreign_key(batch_op.f('contenu_id_prompt_fkey'), 'prompt', ['id_prompt'], ['id'])

    # ### end Alembic commands ###
