"""add multimodal on content

Revision ID: 1d9a54cf7770
Revises: e06fd536b74b
Create Date: 2025-10-03 16:13:38.016263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d9a54cf7770'
down_revision = 'e06fd536b74b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contenu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contenu_structure', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contenu', schema=None) as batch_op:
        batch_op.drop_column('contenu_structure')

    # ### end Alembic commands ###
