"""fixing change user to utilisateur

Revision ID: 4c687c30cccf
Revises: 801324e5dc5f
Create Date: 2025-07-09 12:01:58.444941

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4c687c30cccf'
down_revision = '801324e5dc5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('prenom', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('mot_de_passe', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('type_compte', postgresql.ENUM('admin', 'user', 'free', 'premium', name='typecompteenum'), autoincrement=False, nullable=False),
    sa.Column('date_creation', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('actif', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('email', name=op.f('users_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
