"""add cascade on plateform foreign key

Revision ID: 4d623af703b6
Revises: 1d9a54cf7770
Create Date: 2025-10-21 23:21:20.726184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d623af703b6'
down_revision = '1d9a54cf7770'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oauth_state', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('oauth_state_plateforme_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'plateforme_config', ['plateforme_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('utilisateur_plateforme', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('utilisateur_plateforme_plateforme_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'plateforme_config', ['plateforme_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur_plateforme', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('utilisateur_plateforme_plateforme_id_fkey'), 'plateforme_config', ['plateforme_id'], ['id'])

    with op.batch_alter_table('oauth_state', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('oauth_state_plateforme_id_fkey'), 'plateforme_config', ['plateforme_id'], ['id'])

    # ### end Alembic commands ###
