"""add modele plateforme et publication

Revision ID: 4e45ab3b736d
Revises: 00c45fdd16f7
Create Date: 2025-09-24 16:49:52.487596

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4e45ab3b736d'
down_revision = '00c45fdd16f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plateformes', schema=None) as batch_op:
        batch_op.alter_column('nom_compte',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.create_unique_constraint('unique_user_platform', ['id_utilisateur', 'nom_plateforme'])
        batch_op.drop_column('parametres_publication')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plateformes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parametres_publication', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_constraint('unique_user_platform', type_='unique')
        batch_op.alter_column('nom_compte',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
