"""change to autoincrement content id

Revision ID: 680f844fbc9f
Revises: f00073cbb279
Create Date: 2025-07-25 18:19:46.177374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '680f844fbc9f'
down_revision = 'f00073cbb279'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contenu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_model', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('contenu_id_modele_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'model_ia', ['id_model'], ['id'])
        batch_op.drop_column('id_modele')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contenu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_modele', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('contenu_id_modele_fkey'), 'model_ia', ['id_modele'], ['id'])
        batch_op.drop_column('id_model')

    # ### end Alembic commands ###
