"""add cascade on publication foreign key SET NULL

Revision ID: 6a7f589101b4
Revises: 4d623af703b6
Create Date: 2025-10-21 23:49:57.699270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a7f589101b4'
down_revision = '4d623af703b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.alter_column('id_plateforme',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('publications_id_utilisateur_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('publications_id_plateforme_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('publications_id_contenu_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'contenu', ['id_contenu'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'utilisateurs', ['id_utilisateur'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'plateforme_config', ['id_plateforme'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('publications_id_contenu_fkey'), 'contenu', ['id_contenu'], ['id'])
        batch_op.create_foreign_key(batch_op.f('publications_id_plateforme_fkey'), 'plateforme_config', ['id_plateforme'], ['id'])
        batch_op.create_foreign_key(batch_op.f('publications_id_utilisateur_fkey'), 'utilisateurs', ['id_utilisateur'], ['id'])
        batch_op.alter_column('id_plateforme',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
