"""fix enum issue

Revision ID: 801324e5dc5f
Revises: 
Create Date: 2025-07-09 09:02:07.520707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '801324e5dc5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('prenom', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('mot_de_passe', sa.String(length=200), nullable=False),
    sa.Column('type_compte', sa.Enum('admin', 'user', 'free', 'premium', name='typecompteenum'), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
