"""add cutom prompt

Revision ID: c5d321c8e60d
Revises: 0e543c7d7dc3
Create Date: 2025-11-06 07:39:38.132672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5d321c8e60d'
down_revision = '0e543c7d7dc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contenu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_prompt', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contenu', schema=None) as batch_op:
        batch_op.drop_column('custom_prompt')

    # ### end Alembic commands ###
