"""modification publication et ajout token

Revision ID: d37a9c8f5cd3
Revises: 6a7f589101b4
Create Date: 2025-10-24 12:09:51.066131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd37a9c8f5cd3'
down_revision = '6a7f589101b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plateforme', sa.String(length=50), nullable=False))
        batch_op.drop_constraint(batch_op.f('publications_id_plateforme_fkey'), type_='foreignkey')
        batch_op.drop_column('id_plateforme')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_plateforme', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('publications_id_plateforme_fkey'), 'plateforme_config', ['id_plateforme'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('plateforme')

    # ### end Alembic commands ###
