"""Add id_projet in content table

Revision ID: e06fd536b74b
Revises: eac79c208406
Create Date: 2025-10-03 10:58:57.543487

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e06fd536b74b'
down_revision = 'eac79c208406'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plateformes')
    with op.batch_alter_table('contenu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_projet', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'projets', ['id_projet'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contenu', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_projet')

    op.create_table('plateformes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_utilisateur', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nom_plateforme', postgresql.ENUM('facebook', 'linkedin', 'instagram', 'twitter', name='typeplateformeenum'), autoincrement=False, nullable=False),
    sa.Column('nom_compte', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('id_compte_externe', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('token_expiration', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('statut_connexion', postgresql.ENUM('connecte', 'deconnecte', 'expire', 'erreur', name='statutconnexionenum'), autoincrement=False, nullable=True),
    sa.Column('permissions_accordees', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('parametres_publication', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('limite_posts_jour', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('posts_publies_aujourd_hui', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('derniere_publication', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('derniere_synchronisation', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('actif', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('date_creation', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_modification', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['utilisateurs.id'], name=op.f('plateformes_id_utilisateur_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('plateformes_pkey'))
    )
    # ### end Alembic commands ###
