"""plateforme change

Revision ID: eac79c208406
Revises: 4e45ab3b736d
Create Date: 2025-09-25 10:12:15.550459

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eac79c208406'
down_revision = '4e45ab3b736d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plateformes')
    with op.batch_alter_table('historiques', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('historiques_id_plateforme_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'plateforme_config', ['id_plateforme'], ['id'])

    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('publications_id_plateforme_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'plateforme_config', ['id_plateforme'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('publications_id_plateforme_fkey'), 'plateformes', ['id_plateforme'], ['id'])

    with op.batch_alter_table('historiques', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('historiques_id_plateforme_fkey'), 'plateformes', ['id_plateforme'], ['id'])

    op.create_table('plateformes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_utilisateur', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nom_plateforme', postgresql.ENUM('facebook', 'linkedin', 'instagram', 'twitter', name='typeplateformeenum'), autoincrement=False, nullable=False),
    sa.Column('nom_compte', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('id_compte_externe', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('token_expiration', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('statut_connexion', postgresql.ENUM('connecte', 'deconnecte', 'expire', 'erreur', name='statutconnexionenum'), autoincrement=False, nullable=True),
    sa.Column('permissions_accordees', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('parametres_publication', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('limite_posts_jour', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('posts_publies_aujourd_hui', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('derniere_publication', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('derniere_synchronisation', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('actif', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('date_creation', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_modification', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['utilisateurs.id'], name=op.f('plateformes_id_utilisateur_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('plateformes_pkey'))
    )
    # ### end Alembic commands ###
