"""fix content[

Revision ID: f00073cbb279
Revises: b38f32d63c6e
Create Date: 2025-07-25 17:12:45.168508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f00073cbb279'
down_revision = 'b38f32d63c6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contenu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('id_template', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('id_prompt', sa.Integer(), nullable=True))
        batch_op.alter_column('id_utilisateur',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('id_modele',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('texte',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'prompt', ['id_prompt'], ['id'])
        batch_op.create_foreign_key(None, 'templates', ['id_template'], ['id'])
        batch_op.drop_column('id_contenu')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contenu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_contenu', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('texte',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('id_modele',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('id_utilisateur',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('id_prompt')
        batch_op.drop_column('id_template')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
